### ISSUE TITLE
This site have no option to add border-radius

### ISSUE THREAD

**Issue by nicitaacom** [photopea/photopea#6187]
I want to add rounded-full class
```css
.placeholder {
border-radius:50%;
}
```

But it doesn't work

In ctrl+f I also did't found something related that help me to add border radius to this image

![image](https://github.com/photopea/photopea/assets/39565703/2ec341f6-e76e-40d6-8779-bed1f0a29969)
